### ISSUE TITLE
 Issues with Cellpose on macOS using the MPS Backend

### ISSUE THREAD

**Issue by Vijayishwerj** [MouseLand/cellpose#1063]
Hello Cellpose Team,

I am experiencing several issues while using Cellpose for segmentation and training models on my Mac Studio M2 Ultra. I would appreciate your guidance to resolve these problems. Below are the details:

Environment Information

	•	Operating System: macOS
	•	Device: Mac Studio M2 Ultra
	•	Python Version: 3.11.10
	•	Cellpose Version: 3.1.0
	•	Torch Version: 2.5.1
	•	Backend: MPS (Metal Performance Shaders)

Issues Faced

	1.	GPU Incompatibility with Sparse Tensor Operations:
	•	Error: NotImplementedError: Could not run 'aten::_sparse_coo_tensor_with_dims_and_tensors' with arguments from the 'SparseMPS' backend....
	•	This suggests that the MPS backend lacks support for sparse tensor operations, leading to failures during segmentation.
	2.	Fallback to CPU:
	•	When the MPS backend fails, computation falls back to the CPU.
	•	However, warnings about the missing MKL optimizations slow down performance significantly:  WARNING: MKL version on torch not working/installed - CPU version will be slightly slower.

	3.	GPU Training Issues:
	•	The latest version of Cellpose mandates GPU use for training. However, the MPS backend does not complete tasks, and training without a GPU seems impossible.
	4.	Performance Bottleneck:
	•	The fallback to CPU leads to extremely long training times, making it impractical for large datasets.

Run Logs

Attached below is the terminal output with verbose mode enabled, showing the errors and relevant information:
	•	MPS backend available: torch.backends.mps.is_available() returns True.
	•	The operation fails during sparse tensor computation (aten::_sparse_coo_tensor_with_dims_and_tensors).

####
NotImplementedError: Could not run 'aten::_sparse_coo_tensor_with_dims_and_tensors' with arguments from the 'SparseMPS' backend.  ####

	1.	Verified that the MPS backend is correctly installed and available.
	2.	Updated to the latest versions of Cellpose, Python, and PyTorch.
	3.	Attempted fallback to the CPU but encountered performance issues due to lack of MKL support.
	4.	Explored replacing sparse operations with dense ones but encountered compatibility constraints.

Request for Assistance

	1.	GPU Support:
	•	Are there plans to improve sparse tensor compatibility for the MPS backend in future versions?

**Comment by sophiamaedler** [comment]
I've looked into this a little and there seem to be two breaking changes that prevent running cellpose >= 3.1 on an MPS backend: 

1. currently no PyTorch support for sparse operations (see here: https://github.com/pytorch/pytorch/issues/129842)
2. apple GPUs are only single-precision so they do not and probably will never support torch.double/torch.float64 operations. 

Regarding 1:
I would hope that at some point PyTorch will release MPS support for sparse operations. Until then I am not sure how much work it would be to implement some workaround for MPS or if the solution would be to limit MPS use to cellpose 3.0?

Regarding 2:
 I found a few occurrences of `torch.float64` and `torch.double`:
`torch.double`: [cellpose/dynamics.py](https://github.com/MouseLand/cellpose/blob/537c65d329a61d770dcc5f192331a0b1f0a8ba0a/cellpose/dynamics.py#L71)
`torch.float64`: [cellpose/dynamics.py](https://github.com/MouseLand/cellpose/blob/537c65d329a61d770dcc5f192331a0b1f0a8ba0a/cellpose/dynamics.py#L791)

I guess it would be fairly straightforward to add checks here for the MPS backend and ensure that at most torch.float32 is used. I am not sure if this would have any impact on the generated results though. Maybe @carsen-stringer could comment on if replacing occurrences of torch.double/torch.float64 would have any negative consequences . If not I'd be happy to make a PR.

**Comment by OratHelm** [comment]
I think this problem has already been mentioned here: #1034.
A workaround for single-precision has been added in version 3.0.11 of Cellpose, which allows compatibility with the MPS backend.
Sparse operations have been added in subsequent versions of Cellpose. While waiting for a fix to avoid using them with Apple GPUs or for pytorch to implement these functions for MPS, you can go back to version 3.0.11: `pip install git+https://github.com/mouseland/cellpose.git@v3.0.11`

**Comment by carsen-stringer** [comment]
thanks @OratHelm , yeah that would be the current workaround.

@sophiamaedler oh weird, thanks for pointing that out, I assumed pytorch had started supporting MPS double since it was no longer erroring. sorry I don't have an MPS, do you think you could check what is happening when you say "torch.zeros(10, device=torch.device("mps"), dtype=torch.double)"?

the division with 1e-60 we found helped with creating flows which converge for long objects like bacteria (an update with Cellpose3)

**Comment by carsen-stringer** [comment]
FYI I will add an "if" statement, so that only mask creation uses the CPU so that it is possible to run for now in Cellpose 3.1 with MPS for the network inference

**Comment by sophiamaedler** [comment]
@carsen-stringer of course. 

```python
import torch
torch.zeros(10, device=torch.device("mps"), dtype=torch.double)
```

returns
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], [line 1](vscode-notebook-cell:?execution_count=2&line=1)
----> [1](vscode-notebook-cell:?execution_count=2&line=1) torch.zeros(10, device=torch.device("mps"), dtype=torch.double)

TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.
```

I am running from an Apple M3 Max with MacOS 15.1.1 (24B91) running torch 2.5.1.

**Comment by carsen-stringer** [comment]
it should now use the CPU for `get_masks_torch` as a workaround and use `torch.float` instead of `torch.double`, can you please try the latest version? `pip install git+https://github.com/MouseLand/cellpose.git`

**Comment by Vijayishwerj** [comment]
I finally got MPS working on my Mac M2 Ultra and m4 by completely removing all Cellpose files and reinstalling the required libraries from scratch. Since I work with muscles, I found it interesting that Cellpose uses a fixed cell diameter for identification rather than a range. As a suggestion, integrating plugins like Detectron or YOLO11 could be highly beneficial, enabling minimal training to enhance muscle segmentation.

**Comment by sophiamaedler** [comment]
> it should now use the CPU for `get_masks_torch` as a workaround and use `torch.float` instead of `torch.double`, can you please try the latest version? `pip install git+https://github.com/MouseLand/cellpose.git`

@carsen-stringer  This is the test code I used on a small two channel image of nuclei and cell-membranes:

```python
device = torch.device("mps")
model = models.Cellpose(model_type="cyto2", gpu=True, device=device)
masks, _, _, _ = model.eval(
            [image],
            channels=[1, 0],
        )
```

On my old environment using cellpose 3.0.11 it completed with the following print output:

```
..python3.10/site-packages/cellpose/resnet_torch.py:276: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(filename, map_location=device)
..python3.10/site-packages/cellpose/dynamics.py:189: RuntimeWarning: invalid value encountered in divide
  mu /= (1e-60 + (mu**2).sum(axis=0)**0.5)
```

In a new environment running cellpose installed from main I get the following error: 

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[8], line 3
      1 device = torch.device("mps")
      2 model = models.Cellpose(model_type="cyto2", gpu=True, device=device)
----> 3 masks, _, _, _ = model.eval(
      4             [image],
      5             channels=[1, 0],
      6         )

File ~/mambaforge/envs/cellpose_test/lib/python3.11/site-packages/cellpose/models.py:210, in Cellpose.eval(self, x, batch_size, channels, channel_axis, invert, normalize, diameter, do_3D, **kwargs)
    207     diams = diameter
    209 models_logger.info("~~~ FINDING MASKS ~~~")
--> 210 masks, flows, styles = self.cp.eval(x, channels=channels,
    211                                     channel_axis=channel_axis,
    212                                     batch_size=batch_size, normalize=normalize,
    213                                     invert=invert, diameter=diams, do_3D=do_3D,
    214                                     **kwargs)
    215 models_logger.info(">>>> TOTAL TIME %0.2f sec" % (time.time() - tic0))
    217 return masks, flows, styles, diams

File ~/mambaforge/envs/cellpose_test/lib/python3.11/site-packages/cellpose/models.py:453, in CellposeModel.eval(self, x, batch_size, resample, channels, channel_axis, z_axis, normalize, invert, rescale, diameter, flow_threshold, cellprob_threshold, do_3D, anisotropy, dP_smooth, stitch_threshold, min_size, max_size_fraction, niter, augment, tile_overlap, bsize, interp, compute_masks, progress)
    451 for i in iterator:
    452     tic = time.time()
--> 453     maski, flowi, stylei = self.eval(
    454         x[i], batch_size=batch_size,
    455         channels=channels[i] if channels is not None and
    456         ((len(channels) == len(x) and
    457           (isinstance(channels[i], list) or
    458            isinstance(channels[i], np.ndarray)) and len(channels[i]) == 2))
    459         else channels, channel_axis=channel_axis, z_axis=z_axis,
    460         normalize=normalize, invert=invert,
    461         rescale=rescale[i] if isinstance(rescale, list) or
    462         isinstance(rescale, np.ndarray) else rescale,
    463         diameter=diameter[i] if isinstance(diameter, list) or
    464         isinstance(diameter, np.ndarray) else diameter, do_3D=do_3D,
    465         anisotropy=anisotropy, augment=augment, 
    466         tile_overlap=tile_overlap, bsize=bsize, resample=resample,
    467         interp=interp, flow_threshold=flow_threshold,
    468         cellprob_threshold=cellprob_threshold, compute_masks=compute_masks,
    469         min_size=min_size, max_size_fraction=max_size_fraction, 
    470         stitch_threshold=stitch_threshold, dP_smooth=dP_smooth,
    471         progress=progress, niter=niter)
    472     masks.append(maski)
    473     flows.append(flowi)

File ~/mambaforge/envs/cellpose_test/lib/python3.11/site-packages/cellpose/models.py:534, in CellposeModel.eval(self, x, batch_size, resample, channels, channel_axis, z_axis, normalize, invert, rescale, diameter, flow_threshold, cellprob_threshold, do_3D, anisotropy, dP_smooth, stitch_threshold, min_size, max_size_fraction, niter, augment, tile_overlap, bsize, interp, compute_masks, progress)
    532     niter0 = 200 if not resample else (1 / rescale * 200)
    533     niter = niter0 if niter is None or niter == 0 else niter
--> 534     masks = self._compute_masks(x.shape, dP, cellprob, flow_threshold=flow_threshold,
    535                    cellprob_threshold=cellprob_threshold, interp=interp, min_size=min_size,
    536                 max_size_fraction=max_size_fraction, niter=niter,
    537                 stitch_threshold=stitch_threshold, do_3D=do_3D)
    538 else:
    539     masks = np.zeros(0) #pass back zeros if not compute_masks

File ~/mambaforge/envs/cellpose_test/lib/python3.11/site-packages/cellpose/models.py:620, in CellposeModel._compute_masks(self, shape, dP, cellprob, flow_threshold, cellprob_threshold, interp, min_size, max_size_fraction, niter, do_3D, stitch_threshold)
    617 for i in iterator:
    618     # turn off min_size for 3D stitching
    619     min_size0 = min_size if stitch_threshold == 0 or nimg == 1 else -1
--> 620     outputs = dynamics.resize_and_compute_masks(
    621         dP[:, i], cellprob[I],
    622         niter=niter, cellprob_threshold=cellprob_threshold,
    623         flow_threshold=flow_threshold, interp=interp, resize=resize,
    624         min_size=min_size0, max_size_fraction=max_size_fraction,
    625         device=self.device)
    626     if i==0 and nimg > 1:
    627         masks = np.zeros((nimg, shape[1], shape[2]), outputs.dtype)

File ~/mambaforge/envs/cellpose_test/lib/python3.11/site-packages/cellpose/dynamics.py:847, in resize_and_compute_masks(dP, cellprob, niter, cellprob_threshold, flow_threshold, interp, do_3D, min_size, max_size_fraction, resize, device)
    824 def resize_and_compute_masks(dP, cellprob, niter=200, cellprob_threshold=0.0,
    825                              flow_threshold=0.4, interp=True, do_3D=False, min_size=15,
    826                              max_size_fraction=0.4, resize=None, device=torch.device("cpu")):
    827     """Compute masks using dynamics from dP and cellprob, and resizes masks if resize is not None.
    828 
    829     Args:
   (...)
    845         tuple: A tuple containing the computed masks and the final pixel locations.
    846     """
--> 847     mask = compute_masks(dP, cellprob, niter=niter,
    848                             cellprob_threshold=cellprob_threshold,
    849                             flow_threshold=flow_threshold, interp=interp, do_3D=do_3D,
    850                             max_size_fraction=max_size_fraction, 
    851                             device=device)
    853     if resize is not None:
    854         if len(resize) == 2:

File ~/mambaforge/envs/cellpose_test/lib/python3.11/site-packages/cellpose/dynamics.py:923, in compute_masks(dP, cellprob, p, niter, cellprob_threshold, flow_threshold, interp, do_3D, min_size, max_size_fraction, device)
    920 if not do_3D:
    921     if mask.max() > 0 and flow_threshold is not None and flow_threshold > 0:
    922         # make sure labels are unique at output of get_masks
--> 923         mask = remove_bad_flow_masks(mask, dP, threshold=flow_threshold,
    924                                      device=device)
    926 if mask.max() < 2**16 and mask.dtype != "uint16":
    927     mask = mask.astype("uint16")

File ~/mambaforge/envs/cellpose_test/lib/python3.11/site-packages/cellpose/dynamics.py:649, in remove_bad_flow_masks(masks, flows, threshold, device)
    646         dynamics_logger.info("turn off QC step with flow_threshold=0 if too slow")
    647         device0 = torch.device("cpu")
--> 649 merrors, _ = metrics.flow_error(masks, flows, device0)
    650 badi = 1 + (merrors > threshold).nonzero()[0]
    651 masks[np.isin(masks, badi)] = 0

File ~/mambaforge/envs/cellpose_test/lib/python3.11/site-packages/cellpose/metrics.py:256, in flow_error(maski, dP_net, device)
    253     return
    255 # flows predicted from estimated masks
--> 256 dP_masks = dynamics.masks_to_flows(maski, device=device)
    257 # difference between predicted flows vs mask flows
    258 flow_errors = np.zeros(maski.max())

File ~/mambaforge/envs/cellpose_test/lib/python3.11/site-packages/cellpose/dynamics.py:356, in masks_to_flows(masks, device, niter)
    354     return mu
    355 elif masks.ndim == 2:
--> 356     mu, mu_c = masks_to_flows_device(masks, device=device, niter=niter)
    357     return mu
    359 else:

File ~/mambaforge/envs/cellpose_test/lib/python3.11/site-packages/cellpose/dynamics.py:184, in masks_to_flows_gpu(masks, device, niter)
    182 ### run diffusion
    183 n_iter = 2 * ext.max() if niter is None else niter
--> 184 mu = _extend_centers_gpu(neighbors, meds_p, isneighbor, shape, n_iter=n_iter,
    185                          device=device)
    186 mu = mu.astype("float64")
    188 # new normalization

File ~/mambaforge/envs/cellpose_test/lib/python3.11/site-packages/cellpose/dynamics.py:71, in _extend_centers_gpu(neighbors, meds, isneighbor, shape, n_iter, device)
     69     T = torch.zeros(shape, dtype=torch.float, device=device)
     70 else:
---> 71     T = torch.zeros(shape, dtype=torch.double, device=device)
     73 for i in range(n_iter):
     74     T[tuple(meds.T)] += 1

TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.
```

Here the environment specs resulting in the error: 

```
Package                Version
---------------------- --------------------
appnope                0.1.4
asttokens              3.0.0
cellpose               3.1.1.dev90+g3db92b8
comm                   0.2.2
debugpy                1.8.12
decorator              5.1.1
exceptiongroup         1.2.2
executing              2.1.0
fastremap              1.15.0
filelock               3.17.0
fsspec                 2025.2.0
imagecodecs            2024.12.30
importlib_metadata     8.6.1
ipykernel              6.29.5
ipython                8.32.0
jedi                   0.19.2
Jinja2                 3.1.5
jupyter_client         8.6.3
jupyter_core           5.7.2
llvmlite               0.44.0
MarkupSafe             3.0.2
matplotlib-inline      0.1.7
mpmath                 1.3.0
natsort                8.4.0
nest_asyncio           1.6.0
networkx               3.4.2
numba                  0.61.0
numpy                  2.0.2
opencv-python-headless 4.11.0.86
packaging              24.2
parso                  0.8.4
pexpect                4.9.0
pickleshare            0.7.5
pip                    25.0
platformdirs           4.3.6
prompt_toolkit         3.0.50
psutil                 6.1.1
ptyprocess             0.7.0
pure_eval              0.2.3
Pygments               2.19.1
python-dateutil        2.9.0.post0
pyzmq                  26.2.1
roifile                2024.9.15
scipy                  1.15.1
setuptools             75.8.0
six                    1.17.0
stack_data             0.6.3
sympy                  1.13.1
tifffile               2025.1.10
torch                  2.6.0
tornado                6.4.2
tqdm                   4.67.1
traitlets              5.14.3
typing_extensions      4.12.2
wcwidth                0.2.13
wheel                  0.45.1
zipp                   3.21.0
```

**Comment by sophiamaedler** [comment]
@carsen-stringer I found one additional occurrence of torch.double which I fixed in this PR https://github.com/MouseLand/cellpose/pull/1101

The code from above is now working. 

I also did a quick timing benchmark on the same test image comparing 3.0.11 and the version in the PR above. 

Timing results for 3.0.11: 3.37 s ± 40.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
Timing results for main: 2.79 s ± 14.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

So even though we are moving some calculations to the CPU the performance still seems to have improved in comparison to the old version. 

Will be great when PyTorch finally gets around to implementing support for sparse tensors for MPS but until then this seems like a good fix. Thanks for the effort.

**Comment by carsen-stringer** [comment]
thanks for figuring this out and including the timing! glad to see it's at least a bit faster. sorry I need to include both cases in the if statement so I didn't accept the PR (for really large images we also go to float to reduce memory usage on the GPU)

**Comment by sophiamaedler** [comment]
No worries. Glad this is sorted. Hopefully the inclusion of the MPS backend will get easier with time :)
