### ISSUE TITLE
Net Error Cuda out of memory/ import issue

### ISSUE THREAD

**Issue by serrob23** [MouseLand/cellpose#189]
Hello,

I'm having two separate issues. Today I started testing cellpose to segment images of nuclei in 3D.

My first issue is that whenever I try to import cellpose from a jupyter notebook I get a module not found error. However I'm able to run cellpose from the comand line and import it fine in a local ipython instance in anaconda. 

 I was able to get things working with the GUI however. I started off by running it on some very small image volumes, and was able to get some nice results. I then tested the segmentation on some larger volumes ~ 500x500x500 pixels and the model ran successfully on two volumes of that size. 

However now when I try and run the segmentation even very small images I get the following error:

NET ERROR: CUDA out of memory. Tried to allocate 392.00 MiB (GPU 0; 8.00 GiB total capacity; 5.88 GiB already allocated; 48.60 MiB free; 6.10 GiB reserved in total by PyTorch)

Any suggestions?

Thanks!

**Comment by pr4deepr** [comment]
I am getting the same error using the cellpose gui on Windows 10.
I installed it using anaconda and the environment.yml file. 
It works fine when I untick CPU, but of course slower!

**Comment by carsen-stringer** [comment]
re: jupyter notebook not working, I'm not sure why, are you sure that the jupyter notebook is in the `cellpose` envrionment? you can run `!pip list` in the notebook to see the list of packages installed

Sometimes the GPU holds memory, you may have to directly kill processes on the GPU, you can check what's running with `nvidia-smi` in linux. 

@pr4deepr is this only for the 3D version? I will reduce the default batch_size to 4. You can reduce it yourself on the command line or a notebook with the `batch_size` parameter.

**Comment by pr4deepr** [comment]
Hi
  Yes, its for the 3D version. Changing to batch_size=4 worked for me.
Thanks a lot
Pradeep

**Comment by serrob23** [comment]
Hi All, 

Thanks for getting back to me! One thing I've learned over the last few days: I wanted to do some comparisons on how the cyto/nuclear models performed against one another. The data I'm working with is 3D fluorescence data of cancer regions which tend to have enlarged and rather convoluted nuclear structures which is why I thought the cyto model would be worth testing as well.

As it turns out I think the cyto models take up more memory on the GPU to run. When running calibrations for the radius estimate on the data the cyto model gives larger average radii (which makes sense) but I'm assuming that means it is running a higher number of computations per image which I think was causing the error. Once I restarted my system and stuck to just running the nuclear models things are working fine again.


As far as the import issue goes, I'm activating the jupyter notebook after running conda activate cellpose in the anaconda prompt. I created the environment via the yaml file on the repository so unless there's something I'm missing I'm definitely in the active cellpose environment.


Thanks!
Rob

**Comment by serrob23** [comment]
Hello just to follow up, I have tried uninstalling and reinstalling anaconda, setup the environment from the yaml file and am still running into the module not found error when I try to import cellpose in a jupyter notebook. This is even after running:

 !pip install cellpose 

to which I get requirement already satisfied. 

Any advice?

**Comment by pr4deepr** [comment]
Hi Rob
  From what you are saying, you are installing cellpose using Anaconda in your local computer, right? As you have an exclamation mark in front of pip, I feel like you are trying to run pip install cellpose inside the jupyter notebook?? You do NOT need to do this within the notebook if you have already configured the environment using the yml file. 

Can you go through the exact steps you are using for local installation? i.e., is it according to this:
https://github.com/MouseLand/cellpose#local-installation   ?

Also, to 'reinstall' cellpose, you wouldn't need to reinstall anaconda again. You can remove an environment in anaconda using the command:
conda remove --name environment_name_here --all
environment_name_here  should be cellpose or whatever name you use for it.
You can then use the configuration instructions in the link above to try again.

Pradeep

**Comment by carsen-stringer** [comment]
Thanks Pradeep for the advice, sorry @serrob23 not sure the issue.

@serrob23 yes the cyto model will take more memory because the rescaling factor will be larger. The default diameter for the cyto is 30 pixels, so images are resized to that size, whereas for the nuclei model the default diameter is 17 pixels, leading to smaller images used for processing.

**Comment by carsen-stringer** [comment]
I'm closing this issue due to inactivity, please comment if you're still having problems @serrob23

**Comment by Eddymorphling** [comment]
> Hi Yes, its for the 3D version. Changing to batch_size=4 worked for me. Thanks a lot Pradeep

Hi again @pr4deepr . I have been facing the same issue and was wondering the name of the python file in the cellpose env where you changed the batch_size=4? Thank you.
