### ISSUE TITLE
Pb with command line, GPU memory

### ISSUE THREAD

**Issue by mcib3d** [MouseLand/cellpose#397]
Hi,

I try to run cellpose in command line to segment 3D data, but I encounter some weird memory error : 
* If I run using the argument  --diameter 0, it runs using GPU without any problems.
*  If I run using the argument  --diameter 25, it will crash and output this error : _RuntimeError: CUDA out of memory. Tried to allocate 196.00 MiB (GPU 0; 7.76 GiB total capacity; 5.68 GiB already allocated; 64.62 MiB free; 5.93 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF_

**Comment by mcib3d** [comment]
Hi, Thanks for answering. Yes we are using defaults model, and yes the results are not so different; but I was wondering is there was a small bug to be fixed there.

**Comment by carsen-stringer** [comment]
how much gpu memory is used for the `--diameter 0` option? maybe you are already pretty close to the limit?

**Comment by mcib3d** [comment]
Hi, thanks for your reply. The problem disappeared after I updated to the latest version. Thanks again.
