### ISSUE TITLE
Cryptic CUDA error when trying to train from the command line. 

### ISSUE THREAD

**Issue by odinsbane** [MouseLand/cellpose#624]
I have a set of 3D images, that I resliced to get labels. Then I try to train cellpose with the following command.

    python -m cellpose --train --dir ~/working/username/cellpose/training/train --use_gpu --pretrained_model nuclei --learning_rate 0.1 --weight_decay 0.0001 --n_epochs 100 --verbose    

Training fails to start with the following error.

>(cellpose) [username@vis000 training]$ ./train.sh
/camp/home/username/.conda/envs/cellpose/lib/python3.8/site-packages/pyqtgraph/colors/palette.py:1: RuntimeWarning: PyQtGraph supports Qt version >= 5.15, but 5.14.1 detected.
from ..Qt import QtGui
2022-12-08 21:14:23,982 [INFO] WRITING LOG OUTPUT TO /camp/home/username/.cellpose/run.log
2022-12-08 21:14:29,909 [INFO] ** TORCH CUDA version installed and working. **
2022-12-08 21:14:29,910 [INFO] >>>> using GPU
2022-12-08 21:17:22,699 [INFO] 3096 / 3096 images in /camp/home/username/working/msmith/cellpose/training/train folder have labels
2022-12-08 21:17:22,699 [INFO] >>>> during training rescaling images to fixed diameter of 30.0 pixels
2022-12-08 21:17:22,700 [INFO] >> nuclei << model set to be used
2022-12-08 21:17:23,163 [INFO] >>>> model diam_mean =  17.000 (ROIs rescaled to this size during training)
2022-12-08 21:17:42,265 [INFO] flows precomputed
2022-12-08 21:17:47,187 [WARNING] 2056 train images with number of masks less than min_train_masks (5), removing from train set
2022-12-08 21:17:49,082 [INFO] >>>> median diameter set to = 17
2022-12-08 21:17:49,082 [INFO] >>>> mean of training label mask diameters (saved to model) 37.523
2022-12-08 21:17:49,189 [INFO] >>>> training network with 2 channel input <<<<
2022-12-08 21:17:49,189 [INFO] >>>> LR: 0.10000, batch_size: 8, weight_decay: 0.00010
2022-12-08 21:17:49,189 [INFO] >>>> ntrain = 1040
2022-12-08 21:17:49,189 [INFO] >>>> nimg_per_epoch = 1040
Traceback (most recent call last):
  Fi "/camp/home/username/.conda/envs/cellpose/lib/python3.8/runpy.py", line 194, in _run_module_as_main
  turn _run_code(code, main_globals, None,
File "/camp/home/username/.conda/envs/cellpose/lib/python3.8/runpy.py", line 87, in _run_code
  ec(code, run_globals)
  Fi "/camp/home/username/.conda/envs/cellpose/lib/python3.8/site-packages/cellpose/__main__.py", line 362, in <module>
  in()
  Fi "/camp/home/username/.conda/envs/cellpose/lib/python3.8/site-packages/cellpose/__main__.py", line 329, in main
  model_path = model.train(images, labels, train_files=image_names,
  Fi "/camp/home/username/.conda/envs/cellpose/lib/python3.8/site-packages/cellpose/models.py", line 784, in train
  del_path = self._train_net(train_data, train_flows,
  Fi "/camp/home/username/.conda/envs/cellpose/lib/python3.8/site-packages/cellpose/core.py", line 894, in _train_net
  ain_loss = self._train_step(imgi, lbl)
  Fi "/camp/home/username/.conda/envs/cellpose/lib/python3.8/site-packages/cellpose/core.py", line 747, in _train_step
  ss.backward()
  Fi "/camp/home/username/.conda/envs/cellpose/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
  rch.autograd.backward(
  Fi "/camp/home/username/.conda/envs/cellpose/lib/python3.8/site-packages/torch/autograd/__init__.py", line 197, in backward
Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

Which after googling, I came across this thread. https://discuss.pytorch.org/t/runtimeerror-cuda-error-cublas-status-invalid-value-when-calling-cublassgemm-handle-opa-opb-m-n-k-alpha-a-lda-b-ldb-beta-c-ldc/124544/6 

That suggests there is an error with the geometry being used and the data. My input images are 1 channel nuclei stainings. I'm not sure how to specify that the second channel should be zero.

**Comment by odinsbane** [comment]
As an update to this. I read through https://cellpose.readthedocs.io/en/latest/models.html a little more thoroughly and I updated the command by including the arguments --chan 0 --chan2 0 which should use a single channel grayscale image.

python -m cellpose --train --dir ~/working/username/cellpose/training/train --use_gpu --pretrained_model nuclei --learning_rate 0.1 --weight_decay 0.0001 --n_epochs 100 --verbose --chan 0 --chan2 0

**Comment by odinsbane** [comment]
Final update for the night. I also tried with 2 channel images on the cyto model... and I get the same error. Here is my pip freeze if there is a version missmatch or some other. 

>cachetools==5.2.0
cellpose==2.1.1
certifi @ file:///croot/certifi_1665076670883/work/certifi
charset-normalizer==2.1.1
fastremap==1.13.3
google-api-core==2.11.0
google-auth==2.15.0
google-cloud-core==2.3.2
google-cloud-storage==2.6.0
google-crc32c==1.5.0
google-resumable-media==2.4.0
googleapis-common-protos==1.57.0
idna==3.4
imagecodecs==2022.9.26
importlib-metadata==5.1.0
llvmlite==0.39.1
natsort==8.2.0
numba==0.56.4
numpy==1.23.5
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
opencv-python-headless==4.6.0.66
protobuf==4.21.10
pyasn1==0.4.8
pyasn1-modules==0.2.8
PyQt5==5.14.1
PyQt5-Qt5==5.15.2
PyQt5-sip==12.11.0
pyqtgraph==0.13.1
requests==2.28.1
rsa==4.9
scipy==1.9.3
six==1.16.0
tifffile==2022.10.10
torch==1.13.0
tqdm==4.64.1
typing_extensions==4.4.0
urllib3==1.26.13
zipp==3.11.0

**Comment by carsen-stringer** [comment]
what shape are your input images? you could also try in a new environment the non-cuda version of pytorch and see what the error is (perhaps it is a shape error)

**Comment by odinsbane** [comment]
The input image.

    >>> import cellpose.io as io
    >>> x = io.imread("dnas0771.tif")
    >>> x.shape
    (316, 334)

The masks

    >>> x = io.imread("dnas0771_masks.tif")
    >>> x.shape
    (316, 334)

I'll try the new env soon, and add a new comment.

**Comment by carsen-stringer** [comment]
thanks I tried this and couldn't reproduce the error, going to close for now but can reopen

**Comment by odinsbane** [comment]
I tried using the "To install the minimal version of cellpose" and it appears to have installed the nvidia/cuda version again. When I remove the --use_gpu from the command above it uses the CPU and it works. It finished an epoch in 5 minutes. 

The gpu was working fine to make predictions, so I feel the drivers should all be installed correctly. 

When you ran your test, did you include image/mask pairs that were not used because there aren't enough masks in the image? Out of 3096 images, only 1040 are getting used.

**Comment by odinsbane** [comment]
It works now. I re-installed everything. I started from the recommended versions of pytorch.

    conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia

That's using python 3.10 then I activated and installed cellpose. 

    pip install cellpose

It's using torch 1.13.1 and cellpose 2.1.1 so either it was a driver issue or torch changed something between 1.13.0 and 1.13.1 that solved the error I was having.
